### ISSUE TITLE
Does it take variable sized image files? 

### ISSUE THREAD

**Issue by jcopps** [jadevaibhav/Signature-verification-using-deep-learning#3]
Does it take variable sized image files? 
If yes and there is preprocessing done, does it handle 1000x10 and 10x1000? 
Can you please share the accuracy of the tests.

**Comment by jadevaibhav** [comment]
As mentioned, I have used 2 approaches. As I have not used a fully convolutional model, the classifier approach only takes fixed-size images. In the siamese net, even though the fully convolutional net is used, the similarity matrix is used on vectors, so it should have the same dimensions. as long as you keep having same size of anchor, positive and negative image, it will work.
