### ISSUE TITLE
Missing File

### ISSUE THREAD

**Issue by Jkrish1011** [jadevaibhav/Signature-verification-using-deep-learning#6]
It would be great if you can explain how the files in your folder(eg: 'tranfer_20ep_l2+dropout.h5') is coming from ?? 

"x[0].shape" when we try to execute this command the actual output according to you is  "(551, 1117, 3)" is  this but when we execute this same command the output is "(0,).

it would be great if you could shed some light on these .

**Comment by jadevaibhav** [comment]
The file contains trained parameters. As this project was lab work, I can't share those files, you have to train it yourselves.
